### ISSUE TITLE
講師のカレンダー確定画面に否認の仕組みを入れる

### ISSUE THREAD

**Issue by osuke0208** [hachioji-sakura/lms#1045]
否認するときは理由を入れる
どのカレンダーでも入れる

**Comment by hideo-yasui** [comment]
![image](https://user-images.githubusercontent.com/22382436/122178569-a65c2a00-cec1-11eb-9171-3c5ec7a16036.png)

講師が予定を確認するときの画面に、
現状だと、予定確認済みにすることしかできないので、
キャンセルすることができるようにする。

①「この予定を確定しますか？」フォーム追加
name = status
予定を確認済みにする(value=confirm)  or 予定をキャンセルする(value=cancel)
 

②フォームのだし分け
②ー１　予定を確認済みにするを選択した場合
　生徒の確認を必要としない　or　　生徒の確認を必要とする（現行フォーム）
②ー２　予定をキャンセルするを選択した場合
　　キャンセル 理由をお知らせくださいを表示(追加フォーム）
　　textarea, name=remark? cancel_reason?で既存の更新処理拾えたと思う

**Comment by hideo-yasui** [comment]
この修正のゴール
①講師予定確認（confirmへの更新のタイミングで、キャンセルの更新が可能になること）
②キャンセルの通知（講師がキャンセルしたことを事務が拾える仕組み）
　→　課題（別issueで対応予定）
　　イメージとして、slackで事務用の業務チャンネル作ってそこに通知出す想定
