### ISSUE TITLE
生徒がログインできるようにする

### ISSUE THREAD

**Issue by osuke0208** [hachioji-sakura/lms#296]
・生徒のログイン
生徒の詳細画面は関係者全員がアクセスすることができるから
ボタンを追加ダイアログを出す場合は画面遷移なし
ipassを発行するイメージ
生徒詳細に増やした場合は権限とアクションが増える
emailがログインIDになっている
→emailを持てないためtokenを出す

コメントや目標が更新された場合、生徒向けの情報。
→生徒が直接見られる方が良い。
情報共有を生徒の詳細ページで行う場合にアクセスできない。
親がアクセス許可を出す
→ipass発行
→emailフィールドにidを入れる。パスワードをそのまま使う？
→生徒番号を利用したログインはランダム文字列よりは使いやすいかもしれない
tokenは期限の問題

**Comment by osuke0208** [comment]
契約者詳細画面にボタン追加→生徒設定の右側
ボタンを押したらダイアログで情報入力して更新
現在値がどうであれ入力値で更新する

StudentController
　ダイアログ表示用のメソッド追加
　_upadateメソッドにpassword判定を追加
　データの更新はStudentController@updateで行う

blade
　ダイアログの中身をstudent.create_login_formで作成
　パスワードとemailのコンポーネントをいじる必要あり？

login
　生徒がログインできないので、原因調査

**Comment by osuke0208** [comment]
statusが1で体験判定されていた。
statusの件は別のissueへ

**Comment by osuke0208** [comment]
users.satusの意味は下記のとおり
0 ->入会
1 ->仮登録
9 ->退会済

studentsは基本的に1なので、ID、password発行時に0へ更新する
feature/296にて対応中

**Comment by hideo-yasui** [comment]
https://gyazo.com/6b4b7eda9ff2df253f04ee6d0d3248c9
ログインid編集時のmergin-bottom

**Comment by hideo-yasui** [comment]
https://gyazo.com/156184980d67b2d4d366ef6ff4e318be
退会者の場合、システムエラー

**Comment by hideo-yasui** [comment]
![image](https://user-images.githubusercontent.com/22382436/79828048-db164380-83da-11ea-9fd2-4c778b2dca9f.png)

**Comment by hideo-yasui** [comment]
![image](https://user-images.githubusercontent.com/22382436/79828067-e79a9c00-83da-11ea-98b8-74d66797790a.png)
お子様　→　生徒

**Comment by hideo-yasui** [comment]
試したこと
生徒でログイン　ＯＫ
パスワード変更　ＯＫ
メールアドレス変更　ＯＫ
コメント登録　ＯＫ
目標登録　ＯＫ
休み連絡　ＯＫ
生徒設定　ＯＫ
スケジュール一覧表示　ＯＫ
カレンダー表示　ＯＫ

**Comment by hideo-yasui** [comment]
https://github.com/hachioji-sakura/lms/issues/316

**Comment by hideo-yasui** [comment]
パスワード忘れた場合
※生徒メールアドレス変更なら可能
※ログインＩＤの状態だと、メール形式で入れろって怒られる。
