### ISSUE TITLE
userにlocaleを追加する

### ISSUE THREAD

**Issue by osuke0208** [hachioji-sakura/lms#322]
メール送信時にlocaleを見に行くようにする

現在はタグの外国人講師希望のものを見てるため該当タグがあると英語のメールが送信されてしまう。

usersテーブルにlocaleを追加する
defaultはjaで外国人講師のみenに更新する

**Comment by osuke0208** [comment]
![image](https://user-images.githubusercontent.com/61462583/79840169-87165980-83f0-11ea-9963-5891564cf01c.png)

**Comment by osuke0208** [comment]
userが取れているメールとそうでないメール
userが送信相手なのか

userのsendmailに収束させる修正をする

**Comment by osuke0208** [comment]
TrialController-> メールのlocale設定でUserから飛ばしていないのでUserのメソッドに変更

他は置換のみ

**Comment by hideo-yasui** [comment]
locale=enのユーザーでログイン→enで表示：OK
 そのまま続けて画面遷移→enで表示：OK
 **メールアドレス設定→access_keyの受け取りメール　→ jpで送信された　：　NG**
 日本語に変更→jpで表示：OK
 そのまま続けて画面遷移→jpで表示：OK
 **メールアドレス設定→access_keyの受け取りメール　→ 未実施**

locale=jpのユーザーでログイン
 そのまま続けて画面遷移→jpで表示：OK
 メールアドレス設定→access_keyの受け取りメール　→ jpで送信　：　OK
 Englishに変更→enで表示：OK
 そのまま続けて画面遷移→enで表示：OK
 **メールアドレス設定→access_keyの受け取りメール　→ jpで送信　：　NG**


locale=enのユーザーのパスワード再設定のメール：enで送信　：　OK
   メールリンクのパスワード再設定画面：enで表示　：　OK

locale=jpのユーザーのパスワード再設定のメール：jpで送信　：　OK
   メールリンクのパスワード再設定画面：jpで表示　：　OK

**Comment by hideo-yasui** [comment]
ログイン画面をjpに変更
locale=enのユーザーでログイン→enで表示：OK

ログイン画面enに変更
画面がenにならない

**Comment by osuke0208** [comment]
リリース済み
