### ISSUE TITLE
成績管理

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#378]

**Comment by hideo-yasui** [comment]
・ＤＢ
生徒成績（生徒ＩＤ、学校ＩＤ？学部ＩＤ？、学期？、年月日）
└成績科目評点（成績ＩＤ、科目・評点）

**Comment by hideo-yasui** [comment]
v1　写真
後で打ち込む
v2
打ち込む
9科目のテキストボックス
（数値（１－５）、　ＡＢＣ、　〇◎△
↑ここの評点フォーマットが面倒

**Comment by hideo-yasui** [comment]
担任の先生のコメントも欲しい

**Comment by hideo-yasui** [comment]
生活面の評価部分も

**Comment by hideo-yasui** [comment]
時系列で見れること

**Comment by hideo-yasui** [comment]
学期はタイミングによって自動選択

学期は学校によってまちまち
前期・後期
1学期・2学期・3学期

**Comment by hideo-yasui** [comment]
成績名（title）
いつの成績か、1学期2学期3学期
　前期・後期の場合は１と２を使ってもらう

**Comment by hideo-yasui** [comment]
php artisan make:migration create_school_grades_table
php artisan make:migration create_school_grade_details_table
php artisan make:controller SchoolGradeController --resource
php artisan make:controller SchoolGradeDetailController --resource
php artisan make:model Models/SchoolGrade
php artisan make:model Models/SchoolGradeDetail

**Comment by hideo-yasui** [comment]
school_grades の属性
student_id / int　生徒ＩＤ
title / string　タイトル
remark / string 　備考
grade / string 学年コード (e1 :小1、e6 : 小6, j1: 中１・・）
semester_no / int 学期番号（1 or 2 or 3)

**Comment by hideo-yasui** [comment]
**〇school_grades の属性**
student_id / int　生徒ＩＤ
title / string　タイトル
remark / string 　備考
grade / string 学年コード (e1 :小1、e6 : 小6, j1: 中１・・）
semester_no / int 学期番号（1 or 2 or 3) 
s3_alias / string 添付ファイル名
s3_url / string 添付ファイルＵＲＬ

**〇school_grade_detailsの属性**
school_grade_id / int  成績ＩＤ
subject_id / int 科目ＩＤ
report_point / int 評点
remark  / 備考

**Comment by hideo-yasui** [comment]
php artisan make:controller SchoolGradeController --resource
php artisan make:controller SchoolGradeDetailController --resource
php artisan make:model Models/SchoolGrade
php artisan make:model Models/SchoolGradeDetail

**Comment by hideo-yasui** [comment]
**〇view作成**
mkdir .\resources\views\school_grades
copy   .\resources\views\comments\lists.blade.php .\resources\views\school_grades\
copy   .\resources\views\comments\create.blade.php .\resources\views\school_grades\

**Comment by hideo-yasui** [comment]
**〇SchoolGradeControllerの編集**
※ほぼCommentControllerと同じ状態にする
※CommentController開いて、以下コピペして書き換える作業

①使うコンポーネントの定義
use Illuminate\Http\Request;
use App\Models\Comment;
use App\Models\Teacher;
use App\Models\Manager;
use App\Models\Student;
use DB;

コピペし、
※Comment → SchoolGrade

②MilestoneControllerを継承する
Class SchoolGradeController extends MilestoneController

③グルーバル変数の定義
public $domain 
public $table
public function model()  
※comments → school_grades
※Comment → SchoolGrade

③ＣＲＵＤ向けの関数定義（MIlestoneControolerからもらってきた）
public function search
public function _search_scope
public function search
public function create_form
public function update_form
public function show

をとりあえずコピペ

**Comment by hideo-yasui** [comment]
**〇SchoolGrade.phpの編集**
Comment.phpを開いて、ほぼ同じ状態にする

①使うコンポーネントの定義
CommentCheckは使わないので削除

②Milestoneを継承する
Class SchoolGrade extends Milestone


③グルーバル変数の定義
  protected $table = 'lms.comments';
  protected $guarded = array('id');

  public static $rules = array(
      'title' => 'required',
      'body' => 'required',
      'type' => 'required'
  );
  protected $appends = ['type_name', 'create_user_name', 'target_user_name', 'importance_label', 'publiced_date', 'created_date', 'updated_date'];

※comments → school_grades

④SchoolGradeReportとの関係性を定義
  public function reports(){
    return $this->hasMany('App\Models\SchoolGradeReport');
  }

**Comment by hideo-yasui** [comment]
登録フォーム（ver 1）
・添付ファイル
・学期（選択）
・学年（選択）
    [save]   [cancel]

**Comment by hideo-yasui** [comment]
web.phpにを追記

  Route::resource('school_grades','SchoolGradeController');
62行目ぐらいがいいと思う

**Comment by osuke0208** [comment]
@osuke0208 が引き継いでリリース完了
