### ISSUE TITLE
学校管理

### ISSUE THREAD

**Issue by osuke0208** [hachioji-sakura/lms#379]

**Comment by hideo-yasui** [comment]
学校
└学部

生徒-学部id？ or 学校id？

・t学校
学校名
所在地
ＵＲＬ

・t学部・学科
学校id
学部・学科名

**Comment by hideo-yasui** [comment]
学部
└学科
とすると、学部しかない学校や、
合格実績データとか紐づけると、
面倒になる。

紐づけるターゲットデータのレイヤーを一つに持ったほうが楽

**Comment by hideo-yasui** [comment]
年間計画、テスト範囲は、学校ではない
学校＋学年＋時期で管理することになる。

**Comment by hideo-yasui** [comment]
【メモ】
テスト範囲のイメージ
親Ａが講師に渡す
講師 or 親Aが、テスト範囲をアップする
（学校ＩＤ、学年のタグがつく）

該当する生徒は、↑の閲覧が可能とか

**Comment by hideo-yasui** [comment]
拡張案
合格実績データ
受験方式

学部学科テーブルにひもづく
　└受験方式（ＡＯ、Ａ、Ｂ（前期・後期））
　　└合格実績データ
　　　　（内申、センターとか模試の点数、面接、・・・、倍率、男女比率）

**Comment by hideo-yasui** [comment]
生徒は、学部学科idを追加

**Comment by hideo-yasui** [comment]
crudで学校・学部を登録する
以下のサイトからサイトクロールでデータを取り込めるとよい
https://www.minkou.jp/hischool/school/2844/
https://gyazo.com/64d925183cd9e6960fdfba50f52c16ee

**Comment by hideo-yasui** [comment]
学校情報自体は、時系列
schools　→　静的
 └ school_infos　→動的・時系列

**Comment by hideo-yasui** [comment]
統合に関して新規
今のところ、統合元を追う気はない

**Comment by osuke0208** [comment]
![IMG_20200702_122627](https://user-images.githubusercontent.com/61462583/86313240-9ff88200-bc5f-11ea-90cf-caacbe5ab947.jpg)

**Comment by hideo-yasui** [comment]
https://www.kyoiku.metro.tokyo.lg.jp/static/high_school/index.html

**Comment by hideo-yasui** [comment]
@engineer-work-take 

①学校のmigrate作成
②学校のtableにいれるためのスクレイピングツールの作成（Seederのイメージ）
③学校のCRUD画面

**Comment by hideo-yasui** [comment]
@engineer-work-take 

スクレイピングツールから取得する学校の情報については、
要望としてはいったん以下の2種類です.

①都立高校の情報
②大学（国立大・私立大）
なるべく一つのサイトから構文解析して、取り出せると楽ですが
著作権の問題があり、とりあえず使ってもよい一次ソースから取得するポリシーで対応することになります。

https://www.kyoiku.metro.tokyo.lg.jp/static/high_school/index.html

いったん、都立高校の情報ソースはこのサイトになりました。

大学の情報を取ってくるＵＲＬはヒアリング中です。
