### ISSUE TITLE
テスト管理

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#380]
【背景】
生徒が、テストをシステムにアップロードできる（写真を想定）
テストに名前・科目・得点をつけ入力できる

データ構造
T:テスト（中間テスト、期末テストなど・・）
 └T:答案（科目＋得点）

**Comment by hideo-yasui** [comment]
【拡張案】
その後、以下のように発展していき、
自学自習コンテンツを作成した際に、テストとして登録できる
自学自習コンテンツは同じ内容を繰り返し実施できる

https://github.com/hachioji-sakura/lms/issues/796

Ｒ１：テストは、答案（ファイル・点数）を持つ
T:テスト
　└T:答案

Ｒ２：テストは、問題（問題文/配点）を持つ
　　　問題は、解答欄を持つ
　　　解答欄は、解答を持つ（解答があれば自動採点可能）
T:テスト
　└T:問題
　　└T:解答欄
　　└T:解答

Ｒ３：答案は回答データを持つ
　　　答案は実施された日時を記録する
T:答案
　└回答データ

**Comment by osuke0208** [comment]
https://lh3.googleusercontent.com/bEMBkwmQX8G2PNeIXdU_FWZlGCH3ZqlQJ8N4W-Wg9JmC8_7a13Jfn3ye3zUyNbAJohBEPoSTC1if2RTcap5mKJ6zimcyZT37YQ3UTY1hp5zIVKY3EhxK5T5d0m4YpMxr_xwEo2wcj7_WnK3101JAHUeWW3xRhdLgg3Ny-Of88VjvO42k9t8eT8BA7YfBBt25r4I0L_TaV9kDbmc_CMG9QxK6HwrIA9fLPi3PBs1_U-2pqqh-usHMovnbOiBI7cPnvoyshvg4Oz8Jw4ajZ4GFiHEqrjEkfGZyvih6HuWNdx_qb6i0bq_59EcZ7JuLUviA5LL7-Tebr7VnulZNowe8oPbpBginAPJxPnax7STwdK05gd868rFrP2b8IkjSpNd1M2X574HmVOvUGubyP5ZVtFEAblddfpAJ69esegXeHPlftQHnLKnWuJnt_YOo1pcbqJ7m0AhwHUADDA2HveLC36hQ1_emJFyHZgvex_AVGacUCeQVCdoxROGhAnhSqX4KHimj1_wPEUVhCfOndFNexOlr9KP1V4tB4aJHYYsAvIvgRQKcedWshkI6Kv4pZR1yF66Z25jqV7AtORXu9OYPrcy7XYP7WZaHCrrlf5F_35sTzBQaLf4i1DZdtbMnT6Prn3HMQdiiZD1RMM3nW1Lo-4sFoNMGMrZQnH5acuJSOtG4_9y_5I3iilx8e2_-tA=w733-h977-no?authuser=0

**Comment by osuke0208** [comment]
答案の束＝テストとして実装
答案昨日はテスト以外のコンテンツにも対応できる
問題冊子としての機能は別途

リリース済み
