### ISSUE TITLE
担当講師を変更できる仕組み（メンテ用・代講申請用）

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#529]

**Comment by osuke0208** [comment]
講師の変更　処理順

武井 740 to 谷口 713

8/31 おばた
calendar_id = 30990
schedule_id = 28847

calendar user_id -> 713
members user_id 740->713
tbl_schedule_onetime 武井 -> 谷口　hachiojisakura_managementのtbl_teacherのidで変更する。user->tagsのNoと一致していると嬉しい

先生に通知を送る

もともとある代講機能は休講とセットになっている
target_modelに休講がある
