### ISSUE TITLE
イベント登録ーイベント通知機能

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#607]

**Comment by kougetu2001** [comment]
・イベント登録画面の利用者は「事務」
・イベント登録される想定メンバーは「先生」「生徒」

フェーズ１：指定された「先生」「生徒」にメール送信
フェーズ２：メールを受け取ったメンバーが回答する画面作成

**Comment by kougetu2001** [comment]
画面上必要な項目
・(ID)
・イベント名　(例：0000年度●期講習受付開始のお知らせ)
・送信対象
・イベント開催期間
・回答有効期間(開始～終了)※①
・備考＋メモ

※①
・8/1～8/31の夏期講習があるとする。
・先生への予定把握期限が7/10～7/20まで
・生徒への予定把握期限が7/20～8/15まで　とする

・補修か受験対策か　とか
・11時～18時まで(時間は1時間単位のチェックボックス)

**Comment by kougetu2001** [comment]
送信対象を事前に選定するためのテーブルを別途作成するにあたり、必要な項目について。

・ID
・イベントID
・ユーザID
・メール送信ステータス
