### ISSUE TITLE
八王子サクラと授業の契約をしていない契約者は、メッセージ機能に関する表示はしない

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#813]
先生あてに送信することはないので、機能自体が不要です。

案として、is_hachiojidakuraというメソッドが生徒にあるので、同様に、student_parentsに追加し、
自分の生徒が一人でもis_hachiojisakura()==trueならば、trueにする

**Comment by hideo-yasui** [comment]
契約者は、入会した場合に、講師と連絡をとったりする
→　入会していなければ、この機能は利用できない（リンクもださない）

生徒が契約しているかどうかは、Models/Student:::is_hachiojisakura()==trueにて判別できる
この生徒が一人でもいる契約者は、メッセージ機能、連絡先一覧などのリンクを表示し利用できる

**Comment by hideo-yasui** [comment]
![image](https://user-images.githubusercontent.com/22382436/115670023-eb615580-a383-11eb-94c6-605e62f7142c.png)
（以下は未契約ならば不要）
・サイドメニュー
　メッセージ
　よくある質問
　休会連絡、退会連絡

**Comment by hideo-yasui** [comment]
![image](https://user-images.githubusercontent.com/22382436/115670175-177cd680-a384-11eb-98d2-050bf4c3badf.png)
（以下は未契約なら不要）
狭めたときにでてくるフッターボタン
　教室連絡先
　メッセージ一覧
　FAQ

**Comment by engineer-work-take** [comment]
修正してみたのですが、認識あってますでしょうか。
また、あわせて動作確認する良い方法ございましたらご教示いただけると幸いです。
よろしくお願いいたします

**Comment by hideo-yasui** [comment]
ひとまず、Student::is_hachiojisakura()==trueならば、契約した生徒で、
契約者＝契約した生徒を一人以上持つ親でOKです。
