### ISSUE TITLE
宿題登録を簡易的に行いたい

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#865]
●背景
・宿題を入力しやすくしたい
・宿題を出す場合は、学習記録に付随する感じでだす
（サブタスク説）

●とりま対応
学習記録一覧の
学習記録(list-item)に宿題登録ボタンを追加

その場合、付随する学習記録の内容を転記した感じで、
宿題の登録フォームを表示する
parent_task_idを入れておく
　階層のような表示はいったんやらない

**Comment by osuke0208** [comment]
コピー機能にて様子見
