### ISSUE TITLE
月末未承認の講師への対応

### ISSUE THREAD

**Issue by hideo-yasui** [hachioji-sakura/lms#888]
①月末未承認の講師を検索したい
②月末未承認の講師へ催促メールを出したい

**Comment by osuke0208** [comment]
月末未承認とは？
"status が fix" かつ "checked_atがnull"のuser_claendarを持っている

**Comment by osuke0208** [comment]
①
講師一覧のフィルタ(画像の一番右のボタンのフォーム)に月末未承認チェックボックスを足す
講師のscopeも合わせて追加する

![image](https://user-images.githubusercontent.com/61462583/125730348-01ca00f2-0430-4909-b4de-5f48722dbfbf.png)

**Comment by osuke0208** [comment]
②
催促メールはバッチで送信する
DailyProcCommandにて日時のメール送信を行っている
このコマンドにメソッドを追加して、①で追加したスコープに該当する講師にメール送信する

**Comment by osuke0208** [comment]
メールの文面はいったん暫定で作ってみてください。
